'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Edit_Chart_of_Account

    '''<summary>
    '''chkcurass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkcurass As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkrecevables control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkrecevables As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkinven control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkinven As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkprepaid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkprepaid As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkfixass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkfixass As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkpaya control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkpaya As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkbebt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbebt As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkequ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkequ As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkrev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkrev As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkcogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkcogs As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkopexp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkopexp As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkotherexp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkotherexp As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkaccum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkaccum As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtAcCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAcCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtclassid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtclassid As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtstudid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstudid As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAcName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAcName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAcagroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAcagroup As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlcashflow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlcashflow As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnsave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnsave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btncancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btncancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtAcSubGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAcSubGroup As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAcCate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAcCate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtocbfy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtocbfy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtcogm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcogm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtcashflow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcashflow As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtlocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlocation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtcomp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcomp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtfont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfont As Global.System.Web.UI.WebControls.HiddenField
End Class
