'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Edit_leatners_Current_Class

    '''<summary>
    '''ddlStudent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStudent As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtmyclass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmyclass As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlclass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlclass As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtstudid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstudid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtclassid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtclassid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtfont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfont As Global.System.Web.UI.WebControls.HiddenField
End Class
