'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Site

    '''<summary>
    '''head control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents head As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''logo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logo As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblcompname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcompname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hypmyreg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypmyreg As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hyadmiform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyadmiform As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hystudlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hystudlist As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HyperLink4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink4 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hystudlistbyclass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hystudlistbyclass As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hyadmanabyyr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyadmanabyyr As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hyadmbyterm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyadmbyterm As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hyadmilistbyyr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyadmilistbyyr As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hyeitphtot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyeitphtot As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HyperLink3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink3 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hymrkatten control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hymrkatten As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hyclsass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyclsass As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypclstest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypclstest As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hyphomewrk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyphomewrk As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypeams control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypeams As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypcont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypcont As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypindivi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypindivi As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypupload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypupload As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypcontent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypcontent As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hystfform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hystfform As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hystflst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hystflst As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypssnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypssnit As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypincome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypincome As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypyrlproc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypyrlproc As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypyroll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypyroll As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hyppayslip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyppayslip As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HyperLink1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink1 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HyperLink2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink2 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hychtofacc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hychtofacc As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hycntlst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hycntlst As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hyschstm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyschstm As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hyjurent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyjurent As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hyrecschfe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyrecschfe As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hyschslst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyschslst As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hydeblist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hydeblist As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hyedschstm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyedschstm As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hytrns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hytrns As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hydpst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hydpst As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hywthd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hywthd As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hytrnsf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hytrnsf As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hybnkstm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hybnkstm As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hytbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hytbl As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypls As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hybalsht control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hybalsht As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hychsflw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hychsflw As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hychgequ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hychgequ As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hyschinfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyschinfo As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hymsgcnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hymsgcnt As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hyacadar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyacadar As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hyadfebils control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyadfebils As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hylrnatres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hylrnatres As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hyrmvclsdup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyrmvclsdup As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hyadcls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyadcls As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hyedcurcls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyedcurcls As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''adsubjt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adsubjt As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hyuslst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyuslst As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hyuscntrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyuscntrl As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypromo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypromo As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hystuacti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hystuacti As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypagesett control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypagesett As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lbluse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbluse As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgstudpic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgstudpic As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ContentPlaceHolder1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentPlaceHolder1 As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''txtregs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtregs As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtnewadmi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtnewadmi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtstudlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstudlist As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtstudlistbyclass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstudlistbyclass As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtadmianayr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadmianayr As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtadmibyterm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadmibyterm As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtadmilistbyyr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadmilistbyyr As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txteditphoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txteditphoto As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtattendance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtattendance As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtclsasssheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtclsasssheet As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtclstext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtclstext As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txthmwrk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthmwrk As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtexms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtexms As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtcont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcont As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtind As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtgroprep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtgroprep As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtclsactivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtclsactivity As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtcontent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcontent As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtstfform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstfform As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtstflist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstflist As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtsnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsnit As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtincome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtincome As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtprlpros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtprlpros As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtpayroll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpayroll As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtslip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtslip As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtchtacc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtchtacc As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtcntlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcntlist As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtschfeestam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtschfeestam As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtjrnent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtjrnent As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtrecschpay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtrecschpay As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtrecadmpay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtrecadmpay As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtschfeelst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtschfeelst As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtdeblst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdeblst As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtpaybills control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpaybills As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txteditschfee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txteditschfee As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtsetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsetup As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtdepsit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdepsit As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtwtdrw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtwtdrw As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txttrnsf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttrnsf As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtbnkstam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbnkstam As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txttb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttb As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtpl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpl As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtbls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbls As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtchflw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtchflw As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtchngequ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtchngequ As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtschinfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtschinfo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtmsgcnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmsgcnt As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtacadar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtacadar As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtadfeesbill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadfeesbill As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtlnrares control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlnrares As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtadclas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadclas As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtedtcurclass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtedtcurclass As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtadsubjt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadsubjt As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtuserlst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtuserlst As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtacscontrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtacscontrl As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtpromo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpromo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtactive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtactive As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtpagsett control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpagsett As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtcompid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcompid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtfont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfont As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtid As Global.System.Web.UI.WebControls.HiddenField
End Class
