'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class User_Control

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlstaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlstaff As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlclass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlclass As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkregs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkregs As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtregs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtregs As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chknewadmi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chknewadmi As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtnewadmi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtnewadmi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkstudlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkstudlist As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtstudlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstudlist As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkstudlistbyclass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkstudlistbyclass As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtstudlistbyclass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstudlistbyclass As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkadmianayr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkadmianayr As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtadmianayr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadmianayr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkadmibyterm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkadmibyterm As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtadmibyterm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadmibyterm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkadmilistbyyr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkadmilistbyyr As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtadmilistbyyr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadmilistbyyr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkeditphoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkeditphoto As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtphoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtphoto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkattendance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkattendance As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtattendance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtattendance As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkclsass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkclsass As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtclsass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtclsass As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkcltst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkcltst As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtcltst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcltst As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkhmwrk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkhmwrk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txthmwrk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthmwrk As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkexmhet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkexmhet As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtexmhet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtexmhet As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkcontsheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkcontsheet As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtcontsheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcontsheet As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkindrep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkindrep As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtindrep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtindrep As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkrepbycls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkrepbycls As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtrepbycls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtrepbycls As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkuploa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkuploa As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtuploa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtuploa As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkcmtent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkcmtent As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtcmtent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcmtent As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkstfform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkstfform As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtstfform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstfform As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkstflist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkstflist As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtstflist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstflist As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chksnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chksnit As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtssnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtssnit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkincome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkincome As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtincome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtincome As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkprlpros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkprlpros As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtprlpros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtprlpros As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkpayroll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkpayroll As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtpayroll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpayroll As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkslip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkslip As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtslip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtslip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkchtacc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkchtacc As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtchtacc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtchtacc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkcntlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkcntlist As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtcntlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcntlist As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkschfeestam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkschfeestam As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtschfeestam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtschfeestam As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkjrnent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkjrnent As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtjrnent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtjrnent As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkrecschpay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkrecschpay As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtrecschpay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtrecschpay As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkrecadmpay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkrecadmpay As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtrecadmpay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtrecadmpay As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkschfeelst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkschfeelst As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtschfeelst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtschfeelst As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkdeblst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkdeblst As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtdeblst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdeblst As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkpaybills control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkpaybills As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtpaybills control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpaybills As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkeditschfee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkeditschfee As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txteditschfee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txteditschfee As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chksetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chksetup As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtsetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsetup As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkdepsit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkdepsit As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtdepsit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdepsit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkwtdrw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkwtdrw As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtwtdrw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtwtdrw As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chktrnsf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chktrnsf As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txttrnsf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttrnsf As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkbnkstam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbnkstam As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtbnkstam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbnkstam As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chktb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chktb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txttb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkpl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkpl As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtpl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpl As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkbls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbls As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtbls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbls As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkchflw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkchflw As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtchflw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtchflw As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkchngequ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkchngequ As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtchngequ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtchngequ As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkschinfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkschinfo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtschinfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtschinfo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkmsgcnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkmsgcnt As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtmsgcnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmsgcnt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkacadar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkacadar As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtacadar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtacadar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkadfeesbill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkadfeesbill As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtadfeesbill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadfeesbill As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chklnrares control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chklnrares As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtlnrares control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlnrares As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkadclas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkadclas As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtadclas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadclas As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkedtcurclass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkedtcurclass As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtedtcurclass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtedtcurclass As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkadsubjt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkadsubjt As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtadsubjt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadsubjt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkuserlst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkuserlst As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtuserlst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtuserlst As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkacscontrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkacscontrl As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtacscontrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtacscontrl As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkpromo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkpromo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtpromo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpromo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkactive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkactive As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtactive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtactive As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkpage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkpage As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtpage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpage As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnsave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnsave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btncancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btncancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtAcSubGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAcSubGroup As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAcCate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAcCate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtocbfy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtocbfy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtcogm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcogm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtusers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtusers As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txttimer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttimer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtlocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlocation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtcomp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcomp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtfont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfont As Global.System.Web.UI.WebControls.HiddenField
End Class
